dataset:
  data_path: /kaggle/input/datasets/tuannv0505/flickr8k/flickr8k
  latents_path: /kaggle/input/datasets/tuannv0505/flickr8k-latents-train/Flickr8k_latents_train
  text_embeds_path: /kaggle/input/datasets/tuannv0505/flickr8k-embeddings-train/Flickr8k_embeddings_train
  image_size: 256
  num_workers: 4

model:
  name: DiT-S/2
  vae: ema

training:
  epochs: 1000
  global_batch_size: 256
  global_seed: 0
  optimizer:
    lr: 1e-4
    weight_decay: 0

sampling:
  cfg_scale: 4
  num_sampling_steps: 1000
  prompt: A man riding a bicycle.

logging:
  results_dir: results
  log_every: 100
  ckpt_every: 100
  resume_ckpt: null