dataset:
  data_path: /kaggle/input/datasets/tuanbeomap/flickr8k/flickr8k
  latents_path: /kaggle/input/datasets/tuanbeomap/flickr8k-latents-train/Flickr8k_latents_train
  text_embeds_path: /kaggle/input/datasets/tuanbeomap/flickr8k-embeddings-train/Flickr8k_embeddings_train
  image_size: 256
  num_workers: 4
  p_uncond: 0.1

model:
  name: DiT-S/2
  vae: ema

training:
  epochs: 5000
  global_batch_size: 128
  global_seed: 0
  optimizer:
    lr: 1e-4
    weight_decay: 0

sampling:
  model_type: ema
  cfg_scale: 2
  num_sampling_steps: 250
  prompt: A dog is running in the snow.

logging:
  results_dir: results
  log_every: 100
  ckpt_every: 300
  resume_ckpt: /kaggle/input/datasets/tuanbeomap/checkpoint-0421200/checkpoint_0421200.pt
  is_save_to_s3: true